-- Rei-do-Red Football Intelligence Engine
-- Shadow-mode storage only. Does not modify legacy tables.

create table if not exists public.football_intelligence_shadow_snapshots (
    id bigint generated by default as identity primary key,
    fixture_id bigint not null,
    generated_at timestamptz not null,
    model_name text not null,
    expected_home_goals double precision not null,
    expected_away_goals double precision not null,
    data_quality double precision not null check (data_quality >= 0 and data_quality <= 1),
    model_quality double precision not null check (model_quality >= 0 and model_quality <= 1),
    assessments jsonb not null default '[]'::jsonb,
    created_at timestamptz not null default now()
);

create index if not exists idx_fi_shadow_fixture_generated
    on public.football_intelligence_shadow_snapshots (fixture_id, generated_at desc);

comment on table public.football_intelligence_shadow_snapshots is
    'Append-only snapshots from the Rei-do-Red Football Intelligence Engine running in SHADOW mode.';
